title: ML4MS
description: Machine Learning for Materials Science
theme: jekyll-theme-tactile
show_downloads: false
google_analytics: 
permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
